### ISSUE TITLE
Rename folder name 

### ISSUE THREAD

**Issue by mzp23** [BinaryStudioAcademy/thread-js#1]
rename folder privateRoute (client/src/containers/privateRoute ) to PrivateRoute or an error occurs when you run the application
`./src/containers/Routing/index.jsx
Cannot find file: 'index.jsx' does not match the corresponding name on disk: '.\src\containers\PrivateRoute\privateRoute'.`

**Comment by AlikRakhmonov** [comment]
fixed. thanks!
